### ISSUE TITLE
UUID Error

### ISSUE THREAD

**Issue by LoToRTv** [Beelzebu/Coins#16]
Hello thx for last help. I have new eror : "[Coins] An internal error has occurred cheking if the player: 195facc5-88dc-4939-99c1-b2173cb12316 exists in the database."

I think there is a mistake in this i use this plugin and he change player uuid.......could you look at it? THX

https://www.spigotmc.org/resources/%E2%96%A0-jpremium-2-0-%E2%96%A0-advanced-login-system-with-auto-login-premium-players-%E2%96%A0-1-8-1-13-%E2%96%A0.27766/

**Comment by LoToRTv** [comment]
it would be possible to add coins to the name only ?

**Comment by LoToRTv** [comment]
+ /coins NAME say error on console You do not have a permission to tab-complete a command!

**Comment by Beelzebu** [comment]
Hi, you'll need to set Online Mode to false in Coins so the plugin will try to update uuid data instead of usernames that are used for read and write operations.
Version 2 of the plugin allows you to use usernames in commands but it must match the exact username that is in the database, this is a problem solved in version 3 of the plugin that is still in development.
The error that you see in console about tab completion isn't from coins and can be from another plugin installed on the server, tab complete should be working from console.

**Comment by LoToRTv** [comment]
I have bungee coins 
pls add support auto update coins ? 
example:
write a command on server1: coins give 300 name
on server2 autoupdate coins :)

**Comment by Beelzebu** [comment]
The plugin is already trying to update the data using the messaging system between bungeecord and bukkit, you only need to install the plugin in bungeecord and enable bungeecord in spigot.yml
